### ISSUE TITLE
Catch all e-mail forwarding

### ISSUE THREAD

**Issue by shechter** [seeebiii/ses-email-forwarding#447]
Great package @seeebiii Sebastian!

There's an issue with setting up a catch-all forwarder for an entire domain or subdomain.

<img width="479" alt="image" src="https://user-images.githubusercontent.com/4543920/174655815-eced8649-5987-4ee2-bd35-a6de8f8ea295.png">

Your emailMapping definition takes a "subdomain.domain.com" format, which is what's needed to create the forwarding rule in SES.

However, the `aws-lambda-ses-forwarder` package is expecting the input to be "@subdomain.domain.com", with the leading "@".

I was thinking that when you write the mapping to SSM, if the `receiveEmail` is not a valid e-mail, but rather a subdomain or domain, then you prepend "@" before saving in SSM so that `aws-lambda-ses-forwarder` can properly forward email from the entire (sub)domain.

https://github.com/seeebiii/ses-email-forwarding/blob/0971f77e8e14f7887d0553db52dbeb4a9dc15ce4/src/email-forwarding-rule.ts#L139

**Comment by seeebiii** [comment]
Hi @shechter , thanks for the bug report! I'll look into it soon-ish or if you want to provide a PR, I'm happy to receive a contribution and accept it.

**Comment by seeebiii** [comment]
Wow after one year I fixed this bug... Sorry for the long delay :/ However, I chose to use `@example.org` to indicate that the whole domain should be covered (the same pattern is used in the `aws-lambda-ses-forwarder` library).
