### ISSUE TITLE
nodejs12.x is no longer supported

### ISSUE THREAD

**Issue by ericmillsio** [seeebiii/ses-email-forwarding#449]
EmailForwardingRuleSet/EmailForwardingRule-0/EmailForwardingFunction: Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 124fd8f3-53b5-478e-a8e7-ed5075c5e7fe)" (RequestToken: eafdb84e-8fb3-0283-1223-881c1581b1f2, HandlerErrorCode: InvalidRequest)

==========

Can we get this bumped up?

**Comment by seeebiii** [comment]
@ericmillsio Thanks for mentioning! Updated to Node18 but also had to update many more dependencies, hence I did a major version upgrade.

**Comment by ericmillsio** [comment]
So fast, thank you!
